### ISSUE TITLE
裁切后上传云存储会报路径找不到。

### ISSUE THREAD

**Issue by z-perfe** [weiwait/dcat-cropper#5]
vendor\weiwait\dcat-cropper\src\Form\Field\Cropper.php
的 prepareInputValue 方法中 
$this->callInterventionMethods($this->getStorage()->path($file), $this->getStorage()->mimeType($file));

修改为 
$this->callInterventionMethods($this->getStorage()->path($file), null);

正常。

**Comment by weiwait** [comment]
> vendor\weiwait\dcat-cropper\src\Form\Field\Cropper.php 的 prepareInputValue 方法中 $this->callInterventionMethods($this->getStorage()->path($file), $this->getStorage()->mimeType($file));
> 
> 修改为 $this->callInterventionMethods($this->getStorage()->path($file), null);
> 
> 正常。
已修复
